<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNoArchivedLastArticles()
    {
        $lastArticles = $this->createQueryBuilder('a')
            ->where('a.archived = 0')
            ->andWhere('a.publicationDate < :now')
            ->orderBy('a.publicationDate', 'DESC')
            ->setParameter('now', new \DateTime())
            ->getQuery()
            ->setMaxResults(3)
            ->getResult();

        return $lastArticles;
    }
}
