<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    public static function available(EventRepository $repository){
        $repo = $repository->createQueryBuilder('e')
            ->leftJoin('e.article','art' )
            ->where('art.event IS NULL')
        ;
        if (isset($_REQUEST['id']) && $_REQUEST['id']) {
            $repo
                ->orWhere('art.id =:article')
                ->setParameter('article',$_REQUEST['id'] );
        }
        return $repo;
    }
}
