<?php

namespace AppBundle\Repository;

/**
 * EventInscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventInscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
