<?php

namespace AppBundle\Repository;

/**
 * NewsletterReceiverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterReceiverRepository extends \Doctrine\ORM\EntityRepository
{
}
