easy_admin:
    site_name: 'EHS Admin'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: 'green'
        assets:
            favicon: '/favicon.ico'
            js:
                - '/ehs/js/tinymce/tinymce.min.js'
                - '/ehs/js/initTiny.js'
        form_theme: 'vertical'
        menu:
            - { label: 'menu.home', route: 'homepage', icon: 'home' }
            - { entity: 'Event', icon: 'calendar' }
            - { entity: 'Article', icon: 'book' }
            - { entity: 'User', icon: 'user-circle-o' }
            - { entity: 'Archive', icon: 'archive' }
            - { entity: 'Contact', icon: 'envelope-o' }
            - { label: 'menu.gallery', route: 'gallery_new', icon: 'camera' }
            - { label: 'menu.newsletter', url: 'https://login.mailchimp.com/', icon: 'paperclip' }
    list:
        max_results: 100

    entities:
        User:
            class: AppBundle\Entity\User
            label: menu.user
            list:
                title: menu.user
                actions:
                    - -new
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
                    - { name: 'user_validate', label: action.validated, type: 'route' }
                fields:
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'address' }
                    - { property: 'zipCode', type: 'text' }
                    - { property: 'city' }
                    - { property: 'phone' }
                    - { property: 'isUptodate', type: 'boolean' }
            edit:
                fields:
                    - { property: 'email' }
                    - { property: 'newsletter' }
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'address' }
                    - { property: 'zipCode', type: 'text' }
                    - { property: 'city' }
                    - { property: 'phone' }
                    - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true,
                      choices: { 'User': 'ROLE_USER', 'Press': 'ROLE_PRESSE', 'Moderator': 'ROLE_ADMIN', 'Administrator': 'ROLE_SUPER_ADMIN' } } }
        Contact:
            class: AppBundle\Entity\Contact
            list:
                actions:
                    - new
                    - -edit
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
            show:
                actions:
                    - -edit
                    - { name: 'answer', label: action.answer, icon: 'mail-reply', css_class: 'btn btn-primary'}

        Event:
            class: AppBundle\Entity\Event
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
                    - { name: 'listRegistered', label: 'action.listRegistered' }
                fields:
                    - id
                    - { property: 'title', type: 'text'}
                    - startDate
                    - placeNumber
                    - archived
                    - inscriptions
            new:
                fields:
                    - { type: 'tab', label: 'Contenu principal', icon: 'leanpub' }
                    - { type: 'group',label: 'event.content', css_class: 'col-md-10' }
                    - { property: 'title', type: 'text' }
                    - presentation
                    - { type: 'group',icon: 'info-circle', css_class: 'col-md-2' }
                    - placeNumber
                    - tag
                    - startDate
            edit:
                fields:
                    - { type: 'tab', label: 'Contenu principal', icon: 'leanpub' }
                    - { type: 'group',label: 'form.content', css_class: 'col-md-10' }
                    - {property: 'aliasPath', type_options: { disabled: disabled}}
                    - { property: 'title', type: 'text' }
                    - presentation
                    - { type: 'group',icon: 'info-circle', css_class: 'col-md-2' }
                    - placeNumber
                    - tag
                    - startDate
                    - { type: 'tab', label: 'Programme', icon: 'calendar' }
                    - { property: 'program', type: 'AppBundle\Form\ProgramType', type_options: { label_attr: { hidden: hidden} } }
        Article:
            class: AppBundle\Entity\Article
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - id
                    - title
                    - tag
                    - publicationDate
                    - createdDate
                    - { property: 'user', label: 'create_modify_by' }
                    - archived
            new:
                fields:
                    - { type: 'group',label: 'form.content', css_class: 'col-md-10' }
                    - { property: 'title', type: 'text'}
                    - { property: 'content', type_options: { required: false} }
                    - { type: 'group',icon: 'info-circle', css_class: 'col-md-2' }
                    - { property: 'createdDate', type_options: { disabled: 'disabled', widget: 'single_text', format: 'dd/MM/Y' } }
                    - publicationDate
                    - tag
                    - { property: 'diapofolder', type: 'AppBundle\Form\DiapoFolderType', type_options: { label_attr: { hidden: hidden} } }
                    - { property: 'event', type: 'entity', class: 'AppBundle\Entity\Event',
                                            type_options: { query_builder: AppBundle\Repository\EventRepository::available }}
            edit:
                fields:
                    - { type: 'group',label: 'form.content', css_class: 'col-md-10' }
                    - {property: 'aliasPath', type_options: { attr: { disabled: disabled} }}
                    - { property: 'title', type: 'text'}
                    - { property: 'content', type_options: { required: false} }
                    - { type: 'group',icon: 'info-circle', css_class: 'col-md-2' }
                    - { property: 'createdDate', type_options: { disabled: 'disabled', widget: 'single_text', format: 'dd/MM/Y' } }
                    - publicationDate
                    - tag
                    - { property: 'diapofolder', type: 'AppBundle\Form\DiapoFolderType', type_options: { label_attr: { hidden: hidden} } }
                    - { property: 'event', type: 'entity', class: 'AppBundle\Entity\Event',
                                            type_options: { query_builder: AppBundle\Repository\EventRepository::available }}

        EventInscription:
            class: AppBundle\Entity\EventInscription
            list:
                dql_filter: 'entity.event = eventId'
                actions:
                    - -search
                    - -edit
                    - -new
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - id
                    - lastname
                    - firstname
                    - phone
                    - email
                    - { property: 'mobility', type: 'boolean' }
                    - addInfo
                    - validated

        Archive:
            class: AppBundle\Entity\Archive
            list:
                actions:
                    - { name: 'show', icon: 'eye', label: false }
                    - { name: 'edit', icon: 'pencil', label: false }
                    - { name: 'delete', icon: 'trash', label: false }
                fields:
                    - id
                    - title
                    - modificationDate
                    - { property: 'user', label: 'create_modify_by' }
                    - createdDate
            new:
                fields:
                    - title
                    - comments
            edit:
                fields:
                    - {property: 'aliasPath', type_options: { attr: { disabled: disabled} }}
                    - title
                    - comments

            show:
                fields:
                    - { property: 'user', label: 'create_modify_by' }
                    - aliasPath
                    - title
                    - comments
                    - createdDate
                    - modificationDate
