easy_admin:
    site_name: 'EHS Admin'
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    design:
        brand_color: 'green'
        assets:
            favicon: '/favicon.ico'
            js:
                - '/ehs/js/tinymce/jquery.tinymce.min.js'
                - '/ehs/js/tinymce/tinymce.min.js'
                - '/ehs/js/initTiny.js'
        form_theme: 'vertical'
        menu:
            - { label: 'menu.home', route: 'homepage', icon: 'home' }
            - { entity: 'Event', icon: 'calendar' }
            - { entity: 'Article', icon: 'book' }
            - { entity: 'User', icon: 'user-circle-o' }
            - label: 'menu.contact'
              children:
                - { entity: Contact, icon: 'envelope-o' }
                - { label: 'menu.mailbox', icon: 'send-o', target: '_blank', url: 'https://mail.ovh.net/roundcube/?_user=contact@ethiquehandicap.comgit ' }

    entities:
        User:
            class: AppBundle\Entity\User
            label: menu.user
            list:
                title: menu.user
                actions:
                    - edit
                    - search
                    - -new
                    - { name: 'user_validate', label: action.validated, type: 'route' }
                fields:
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'address' }
                    - { property: 'zipCode', type: 'text' }
                    - { property: 'city' }
                    - { property: 'phone' }
                    - { property: 'isUptodate', type: 'boolean' }
            edit:
                fields:
                    - { property: 'email' }
                    - { property: 'newsletter' }
                    - { property: 'lastname' }
                    - { property: 'firstname' }
                    - { property: 'address' }
                    - { property: 'zipCode', type: 'text' }
                    - { property: 'city' }
                    - { property: 'phone' }
                    - { property: 'roles', type: 'choice', type_options: { expanded: true, multiple: true,
                      choices: { 'Utilisateur': 'ROLE_USER', 'Presse': 'ROLE_PRESSE', 'Modérateur': 'ROLE_ADMIN', 'Administrateur': 'ROLE_SUPER_ADMIN' } } }
        Contact:
            class: AppBundle\Entity\Contact
            list:
              actions:
                  - -edit
                  - show
            show:
                actions:
                    - -edit
                    - { name: 'answer', label: action.answer, icon: 'mail-reply', css_class: 'btn btn-primary'}

        Event:
            class: AppBundle\Entity\Event
            list:
                fields:
                    - id
                    - { property: 'title', type: 'text'}
                    - startDate
                    - placeNumber
                    - archived
                    - inscriptions
            form:
                fields:
                    - { property: 'title', type: 'text' }
                    - presentation
                    - placeNumber
                    - tag
                    - startDate
            edit:
                fields:
                    - { property: 'program', type: 'AppBundle\Form\ProgramType', type_options: { label_attr: { hidden: hidden} } }
        Article:
            class: AppBundle\Entity\Article
            list:
                fields:
                    - id
                    - createDate
                    - user
                    - title
                    - tag
                    - publicationDate
                    - archived
            form:
                fields:
                    - { property: 'createDate', type_options: { disabled: 'disabled', widget: 'single_text', format: 'dd/MM/Y HH:mm' } }
                    - { property: 'title', type: 'text'}
                    - { property: 'content', type_options: { required: false} }
                    - publicationDate
                    - tag
                    - { property: 'diapofolder', type: 'AppBundle\Form\DiapoFolderType', type_options: { label_attr: { hidden: hidden} } }
            new:
                fields:
                    - { property: 'event', type: 'entity', class: 'AppBundle\Entity\Event',
                                            type_options: { query_builder: AppBundle\Repository\EventRepository::available }}
            edit:
                fields:
                    - { property: 'event', type: 'entity', class: 'AppBundle\Entity\Event',
                                            type_options: { query_builder: AppBundle\Repository\EventRepository::available }}